import { readFileSync, writeFileSync } from "node:fs";
import { basename, resolve, dirname, relative, isAbsolute } from "node:path";
import type { Plugin, ResolvedConfig } from "vite";
import { preprocessCSS } from "vite";
import { compile, compileTypes, type CompileOptions } from "@capsule-css/core";

export interface CapsuleOptions extends CompileOptions {
  dtsOutput?: string; // default: "capsule.d.ts"
}

const PREFIX = "\0capsule-css:";
const SUFFIX = ".js";

function isCapsule(id: string) {
  return id.endsWith(".capsule.css");
}

function toVirtualId(absPath: string) {
  return PREFIX + absPath + SUFFIX;
}

function fromVirtualId(id: string): string | null {
  if (!id.startsWith(PREFIX) || !id.endsWith(SUFFIX)) return null;
  return id.slice(PREFIX.length, -SUFFIX.length);
}

// Resolve the path requested by the dev middleware against the project
// root, returning the absolute filesystem path on success or null when the
// request escapes the root.
//
// The dev server forwards every URL ending in `.capsule.css` to readFileSync.
// A naive `req.url.replace(/^\//, "")` would let a payload such as
// `/../../etc/passwd.capsule.css` read arbitrary files relative to the
// process CWD. We resolve against `root` and reject any result whose
// relative path starts with `..` or is absolute.
export function safeResolveCapsulePath(root: string, url: string): string | null {
  if (!url) return null;
  const clean = url.split("?")[0].split("#")[0];
  if (!clean.endsWith(".capsule.css")) return null;

  const absRoot = resolve(root);
  const requested = resolve(absRoot, "." + clean);
  const rel = relative(absRoot, requested);
  if (rel === "" || rel.startsWith("..") || isAbsolute(rel)) return null;
  return requested;
}

// Strip the `@tag <name>;` directive from a CSS string.
//
// A naive global regex would also match `@tag` text appearing inside a CSS
// string literal (e.g. `content: "@tag foo;"`) or inside a `/* ... */`
// comment. Both are valid CSS that the browser will keep verbatim, so we
// must skip them. We scan the input character by character, transparently
// passing strings and comments through.
export function stripTagDirectives(css: string): string {
  const TAG_RE = /^@tag\s+[a-z][a-z0-9-]*\s*;[ \t]*\n?/;
  let out = "";
  let i = 0;

  while (i < css.length) {
    const ch = css[i];

    if (ch === "/" && css[i + 1] === "*") {
      const end = css.indexOf("*/", i + 2);
      const stop = end < 0 ? css.length : end + 2;
      out += css.slice(i, stop);
      i = stop;
      continue;
    }

    if (ch === '"' || ch === "'") {
      const quote = ch;
      let j = i + 1;
      while (j < css.length) {
        if (css[j] === "\\") { j += 2; continue; }
        if (css[j] === quote) { j++; break; }
        j++;
      }
      out += css.slice(i, j);
      i = j;
      continue;
    }

    if (ch === "@") {
      const m = css.slice(i).match(TAG_RE);
      if (m) {
        // Drop indentation that immediately precedes the directive on the
        // same line, so we don't leave a trailing whitespace-only line.
        let k = out.length;
        while (k > 0 && (out[k - 1] === " " || out[k - 1] === "\t")) k--;
        out = out.slice(0, k);
        i += m[0].length;
        continue;
      }
    }

    out += ch;
    i++;
  }

  return out;
}

export function capsule(options: CapsuleOptions = {}): Plugin {
  const registry = new Map<string, string>();
  const cssMap = new Map<string, string>();
  let config: ResolvedConfig;
  let builtCssFileName: string | null = null;

  function buildDtsBlock(id: string): string {
    const dts = compileTypes(id, options);
    const pattern = "*/" + basename(id);
    return (
      `declare module "${pattern}" {\n` +
      dts.split("\n").map(l => (l ? "  " + l : "")).join("\n") +
      `\n}\n`
    );
  }

  function writeDts() {
    const blocks = [...registry.values()].join("\n");
    const out = config.root + "/" + (options.dtsOutput ?? "capsule.d.ts");
    writeFileSync(out, `// generated by capsule-css — do not edit\n\n` + blocks, "utf8");
  }

  return {
    name: "vite-plugin-capsule-css",
    enforce: "pre",

    configResolved(resolved) {
      config = resolved;
    },

    // Return a virtual module id ending in .js (not .css) so Vite's CSS
    // pipeline never processes these files.
    resolveId(id, importer) {
      if (!isCapsule(id)) return;
      if (id.startsWith(".") && importer) {
        const abs = resolve(dirname(fromVirtualId(importer) ?? importer), id);
        return toVirtualId(abs);
      }
      return toVirtualId(id);
    },

    load(id) {
      const file = fromVirtualId(id);
      if (!file) return null;
      const { js, css } = compile(file, { format: "js", ...options });

      registry.set(file, buildDtsBlock(file));
      writeDts();

      if (config.command === "build") {
        cssMap.set(file, stripTagDirectives(css));
        return js;
      }

      const injection = [
        `const __cap_css = ${JSON.stringify(css)};`,
        `const __cap_id = ${JSON.stringify(file)};`,
        `if (typeof document !== "undefined") {`,
        `  let __s = document.querySelector('[data-cap=' + JSON.stringify(__cap_id) + ']');`,
        `  if (!__s) {`,
        `    __s = document.createElement("style");`,
        `    __s.setAttribute("data-cap", __cap_id);`,
        `    document.head.appendChild(__s);`,
        `  }`,
        `  __s.textContent = __cap_css;`,
        `}`,
        `if (import.meta.hot) {`,
        `  import.meta.hot.on("capsule-css:css-update", ({ id, css }) => {`,
        `    if (id !== __cap_id) return;`,
        `    const el = document.querySelector('[data-cap=' + JSON.stringify(id) + ']');`,
        `    if (el) el.textContent = css;`,
        `  });`,
        `  import.meta.hot.accept();`,
        `}`,
      ].join("\n");

      return injection + "\n" + js;
    },

    async generateBundle() {
      if (cssMap.size === 0) return;
      const parts: string[] = [];
      for (const [file, css] of cssMap) {
        const result = await preprocessCSS(css, file, config);
        parts.push(result.code);
      }
      const combined = parts.join("\n");
      const refId = this.emitFile({ type: "asset", name: "capsule.css", source: combined });
      builtCssFileName = this.getFileName(refId);
    },

    transformIndexHtml() {
      if (!builtCssFileName) return [];
      return [{
        tag: "link",
        attrs: { rel: "stylesheet", href: config.base + builtCssFileName },
        injectTo: "head",
      }];
    },

    handleHotUpdate({ file, server }) {
      if (!isCapsule(file)) return;
      if (!registry.has(file)) return;

      const newDts = buildDtsBlock(file);
      const oldDts = registry.get(file);
      registry.set(file, newDts);
      writeDts();

      const virtualId = toVirtualId(file);
      const mod = server.moduleGraph.getModuleById(virtualId);
      if (mod) server.moduleGraph.invalidateModule(mod);

      if (oldDts === newDts) {
        // CSS-only change: swap style tag in place (no React remount)
        const { css } = compile(file, { format: "js", ...options });
        server.ws.send({ type: "custom", event: "capsule-css:css-update", data: { id: file, css } });
        return mod ? [mod] : [];
      }

      // Structural change (variant/tag/component): full module reload
      return mod ? [mod] : [];
    },

    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (!req.url) return next();
        const requested = safeResolveCapsulePath(config.root, req.url);
        if (!requested) return next();

        try {
          const css = readFileSync(requested, "utf8");
          res.setHeader("Content-Type", "text/css");
          res.end(css);
        } catch {
          next();
        }
      });
    },
  };
}
