import { readFileSync, writeFileSync } from "node:fs";
import { basename, resolve, dirname } from "node:path";
import type { Plugin, ResolvedConfig } from "vite";
import { preprocessCSS } from "vite";
import { compile, compileTypes, type CompileOptions } from "@capsule-css/core";

export interface CapsuleOptions extends CompileOptions {
  dtsOutput?: string; // default: "capsule.d.ts"
}

const PREFIX = "\0capsule-css:";
const SUFFIX = ".js";

function isCapsule(id: string) {
  return id.endsWith(".capsule.css");
}

function toVirtualId(absPath: string) {
  return PREFIX + absPath + SUFFIX;
}

function fromVirtualId(id: string): string | null {
  if (!id.startsWith(PREFIX) || !id.endsWith(SUFFIX)) return null;
  return id.slice(PREFIX.length, -SUFFIX.length);
}

function stripTagDirectives(css: string): string {
  return css.replace(/[ \t]*@tag\s+[a-z][a-z0-9-]*\s*;\n?/g, "");
}

export function capsule(options: CapsuleOptions = {}): Plugin {
  const registry = new Map<string, string>();
  const cssMap = new Map<string, string>();
  let config: ResolvedConfig;
  let builtCssFileName: string | null = null;

  function buildDtsBlock(id: string): string {
    const dts = compileTypes(id, options);
    const pattern = "*/" + basename(id);
    return (
      `declare module "${pattern}" {\n` +
      dts.split("\n").map(l => (l ? "  " + l : "")).join("\n") +
      `\n}\n`
    );
  }

  function writeDts() {
    const blocks = [...registry.values()].join("\n");
    const out = config.root + "/" + (options.dtsOutput ?? "capsule.d.ts");
    writeFileSync(out, `// generated by capsule-css — do not edit\n\n` + blocks, "utf8");
  }

  return {
    name: "vite-plugin-capsule-css",
    enforce: "pre",

    configResolved(resolved) {
      config = resolved;
    },

    // Return a virtual module id ending in .js (not .css) so Vite's CSS
    // pipeline never processes these files.
    resolveId(id, importer) {
      if (!isCapsule(id)) return;
      if (id.startsWith(".") && importer) {
        const abs = resolve(dirname(fromVirtualId(importer) ?? importer), id);
        return toVirtualId(abs);
      }
      return toVirtualId(id);
    },

    load(id) {
      const file = fromVirtualId(id);
      if (!file) return null;
      const { js, css } = compile(file, { format: "js", ...options });

      registry.set(file, buildDtsBlock(file));
      writeDts();

      if (config.command === "build") {
        cssMap.set(file, stripTagDirectives(css));
        return js;
      }

      const injection = [
        `const __cap_css = ${JSON.stringify(css)};`,
        `const __cap_id = ${JSON.stringify(file)};`,
        `if (typeof document !== "undefined") {`,
        `  let __s = document.querySelector('[data-cap=' + JSON.stringify(__cap_id) + ']');`,
        `  if (!__s) {`,
        `    __s = document.createElement("style");`,
        `    __s.setAttribute("data-cap", __cap_id);`,
        `    document.head.appendChild(__s);`,
        `  }`,
        `  __s.textContent = __cap_css;`,
        `}`,
        `if (import.meta.hot) {`,
        `  import.meta.hot.on("capsule-css:css-update", ({ id, css }) => {`,
        `    if (id !== __cap_id) return;`,
        `    const el = document.querySelector('[data-cap=' + JSON.stringify(id) + ']');`,
        `    if (el) el.textContent = css;`,
        `  });`,
        `  import.meta.hot.accept();`,
        `}`,
      ].join("\n");

      return injection + "\n" + js;
    },

    async generateBundle() {
      if (cssMap.size === 0) return;
      const parts: string[] = [];
      for (const [file, css] of cssMap) {
        const result = await preprocessCSS(css, file, config);
        parts.push(result.code);
      }
      const combined = parts.join("\n");
      const refId = this.emitFile({ type: "asset", name: "capsule.css", source: combined });
      builtCssFileName = this.getFileName(refId);
    },

    transformIndexHtml() {
      if (!builtCssFileName) return [];
      return [{
        tag: "link",
        attrs: { rel: "stylesheet", href: config.base + builtCssFileName },
        injectTo: "head",
      }];
    },

    handleHotUpdate({ file, server }) {
      if (!isCapsule(file)) return;
      if (!registry.has(file)) return;

      const newDts = buildDtsBlock(file);
      const oldDts = registry.get(file);
      registry.set(file, newDts);
      writeDts();

      const virtualId = toVirtualId(file);
      const mod = server.moduleGraph.getModuleById(virtualId);
      if (mod) server.moduleGraph.invalidateModule(mod);

      if (oldDts === newDts) {
        // CSS-only change: swap style tag in place (no React remount)
        const { css } = compile(file, { format: "js", ...options });
        server.ws.send({ type: "custom", event: "capsule-css:css-update", data: { id: file, css } });
        return mod ? [mod] : [];
      }

      // Structural change (variant/tag/component): full module reload
      return mod ? [mod] : [];
    },

    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (!req.url?.endsWith(".capsule.css")) return next();
        const path = req.url.replace(/^\//, "");
        try {
          const css = readFileSync(path, "utf8");
          res.setHeader("Content-Type", "text/css");
          res.end(css);
        } catch {
          next();
        }
      });
    },
  };
}
